<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>EasySpawner</AssemblyName>
    <RootNamespace>EasySpawner</RootNamespace>
    <OutputType>Library</OutputType>
    <DebugType>none</DebugType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Config\EasySpawnerConfig.cs" />
    <Compile Include="EasySpawnerPlugin.cs" />
    <Compile Include="Patches\DungeonDBStartPatch.cs" />
    <Compile Include="Patches\ZInputPatcher.cs" />
    <Compile Include="Patches\ZNetSceneShutdownPatch.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="UI\EasySpawnerMenu.cs" />
    <Compile Include="UI\PrefabItem.cs" />
    <Compile Include="UI\PrefabState.cs" />
    <Compile Include="UI\Style.cs" />
    <Compile Include="UI\UIElementDragger.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\EasySpawnerAssetBundle">
      <LogicalName>EasySpawnerAssetBundle</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExPath)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(GameManaged)\assembly_utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(GameManaged)\assembly_guiutils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="gui_framework">
      <HintPath>$(GameManaged)\gui_framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(GameManaged)\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExPath)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>$(BepInExPath)\core\BepInEx.Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GameManaged)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameManaged)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameManaged)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameManaged)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManaged)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(GameManaged)\UnityEngine.UIElementsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameManaged)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
