<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == ''"><LAV_GAME_ROOT></GameRoot>
    <GameManaged>$(GameRoot)\Lords and Villeins_Data\Managed</GameManaged>
    <BepInExPath>$(GameRoot)\BepInEx</BepInExPath>
    <PluginInstallDir>$(BepInExPath)\plugins\LordsAndVilleinsCheats</PluginInstallDir>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
