<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>FM26Trainer</AssemblyName>
    <RootNamespace>FM26Trainer</RootNamespace>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

</Project>
