<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == ''"><FTK_GAME_ROOT></GameRoot>
    <GameManaged>$(GameRoot)\FTK_Data\Managed</GameManaged>
    <BepInExPath>$(GameRoot)\BepInEx</BepInExPath>
    <PluginInstallDir>$(BepInExPath)\plugins\ForTheKingCheats</PluginInstallDir>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
