<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == ''">$(VALHEIM_GAME_ROOT)</GameRoot>
    <GameManaged>$(GameRoot)\valheim_Data\Managed</GameManaged>
    <BepInExPath>$(GameRoot)\BepInEx</BepInExPath>
    <PluginInstallDir>$(BepInExPath)\plugins\EasySpawner</PluginInstallDir>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
