<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == ''">$(ZEDZONE_GAME_ROOT)</GameRoot>
    <GameRoot Condition="'$(GameRoot)' == ''">D:\Program Files (x86)\Steam\steamapps\common\ZED ZONE</GameRoot>
    <LangVersion>10</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
