<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == '' And '$(CLANFOLK_GAME_ROOT)' != ''">$(CLANFOLK_GAME_ROOT)</GameRoot>
    <ModInstallDir>$(GameRoot)\Mods</ModInstallDir>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
